CREATE TABLE SYSTEM_USER
(
  USER_ID           BIGINT not null,
  USER_NAME         VARCHAR(40) not null,
  ENCRYTED_PASSWORD VARCHAR(128) not null,
  ENABLED           BIT not null
) ;

ALTER TABLE SYSTEM_USER ADD CONSTRAINT SYSTEM_USER_PK PRIMARY KEY (USER_ID);
ALTER TABLE SYSTEM_USER	ADD CONSTRAINT SYSTEM_USER_UK UNIQUE (USER_NAME);
--
CREATE TABLE SYSTEM_ROLE
(
    ROLE_ID   BIGINT not null,
    ROLE_NAME VARCHAR(30) not null
) ;

ALTER TABLE SYSTEM_ROLE ADD CONSTRAINT SYSTEM_ROLE_PK PRIMARY KEY (ROLE_ID);
ALTER TABLE SYSTEM_ROLE ADD CONSTRAINT SYSTEM_ROLE_UK UNIQUE (ROLE_NAME);
--
CREATE TABLE USER_ROLE
(
    ID      BIGINT AUTO_INCREMENT not null,
    USER_ID BIGINT not null,
    ROLE_ID BIGINT not null
);

ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLE_PK PRIMARY KEY (ID);
ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLE_UK UNIQUE (USER_ID,ROLE_ID);
ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLE_FK1 FOREIGN KEY (USER_ID) REFERENCES SYSTEM_USER (USER_ID);
ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLE_FK2 FOREIGN KEY (ROLE_ID) REFERENCES SYSTEM_ROLE (ROLE_ID);

--
CREATE TABLE PERSISTENT_LOGINS (
    USER_NAME VARCHAR(64) NOT NULL,   #remember标识对应的用户
    SERIES VARCHAR(64) NOT NULL,      #唯一标识
    TOKEN VARCHAR(64) NOT NULL ,      #令牌，存在客户端的cookie中
    LAST_USED TIMESTAMP NOT NULL ,    #上次使用时间记录
    PRIMARY KEY (SERIES)
);

--
INSERT INTO SYSTEM_USER(USER_ID, USER_NAME, ENCRYTED_PASSWORD, ENABLED)
VALUES (2, 'user1', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1);
INSERT INTO SYSTEM_USER(USER_ID, USER_NAME, ENCRYTED_PASSWORD, ENABLED)
VALUES (1, 'admin1', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1);

--
INSERT INTO SYSTEM_ROLE(ROLE_ID, ROLE_NAME)
VALUES (1, 'ROLE_ADMIN');
INSERT INTO SYSTEM_ROLE(ROLE_ID, ROLE_NAME)
VALUES (2, 'ROLE_USER');

--
INSERT INTO USER_ROLE(USER_ID, ROLE_ID)
VALUES (1,1);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID)
VALUES (1,2);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID)
VALUES (2,2);

--
CREATE TABLE USER_INFO (
    USER_ID BIGINT(20) NOT NULL,
    NICKNAME VARCHAR(64),
    TOKEN VARCHAR(64),
    PRIMARY KEY (USER_ID)
);

--
ALTER TABLE USER_INFO ADD CONSTRAINT USER_INFO_FK1 FOREIGN KEY(USER_ID) REFERENCES SYSTEM_USER(USER_ID)
/**
* SYSTEM_USER：系统用户表，可以自己注册，id由管理分配，若未分配，随机产生6位数，唯一！
* SYSTEM_ROLE: 系统角色表，表示系统中存在的各种角色，不同角色拥有不同权限
*              权限：1表示管理员权限，2表示普通用户权限
* USER_ROLE: 用于绑定用户与角色，
* PERSISTENT_LOGINS: 提供使用 remember_me的备用接口，后期实现
*/